#!bin/sh

echo "${GH_TOKEN}" > ~/.git-credentials
git config --global credential.helper store

git clone -q --depth=1 "${UPSTREAM_REPO:-"https://github.com/thedragonsinn/plain-ub"}" ubot
cd ubot
pip -q install --no-cache-dir -r req*.txt
bash run
